version: "3.9"
services:
  dotnet:
    build:
      context: ./aspdotnet
      dockerfile: Containerfile
      args:
        NAME: ${NAME}
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_NAME: ${IMAGE_NAME}
        IMAGE_VERSION: ${IMAGE_VERSION}
        BASE_REGISTRY: ${BASE_REGISTRY}
        BASE_IMAGE: ${BASE_IMAGE}
        BASE_VERSION: ${BASE_VERSION}
        GPU: ${GPU}
        DOTNET_SEMVER: ${DOTNET_SEMVER}
    image: ${IMAGE_REGISTRY}${IMAGE_NAME}${GPU}:${IMAGE_VERSION}
